### ISSUE TITLE
Some characters do not display.

### ISSUE THREAD

**Issue by NotAKidOnSteam** [AstroDogeDX/CVRX#25]
Some characters do not display in CVRX, like funny avatar names.

![image](https://user-images.githubusercontent.com/37721153/222942696-44dbdd4c-7f12-4a6e-b981-24fa88e9ea93.png)
![image](https://user-images.githubusercontent.com/37721153/222942698-efc966e9-1965-4340-9cd9-d168d81e3110.png)

**Comment by AstroDogeDX** [comment]
Specifically that name is written like an HTML tag and it's getting parsed completely out; will switch to method that parses them into `&gt;`/`&lt;` tags.
