### ISSUE TITLE
Error 401 After Name change

### ISSUE THREAD

**Issue by MerlinK11** [AstroDogeDX/CVRX#41]
hi i have changed my name and not i got the Error Code 401 it is possible to relogin in cvrx ?

[https://prnt.sc/YtNwtpc4Y1yz](url)

**Comment by kafeijao** [comment]
I've fixed that in the code and it will get fix next release.

If you want to fix it you can manually edit/delete the config file.
The file can be found at `C:\Users\YOUR_NAME\AppData\Roaming\CVRX\CVRConfigs\config.json`

You can just delete the `config.json` file. But if you want to keep your configurations, open that file and set the `ActiveUsername` and `ActiveUserID` to `null`, like this:
```
{
    "FileVersion": 1,
    "data": {
        "ActiveUsername": null,
        "ActiveUserID": null,
        "CacheMaxSizeInMegabytes": 1000,
        "CVRExecutable": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ChilloutVR\\ChilloutVR.exe",
        "UpdaterIgnoreVersion": null
    }
}
```
