### ISSUE TITLE
Login via code does not work.

### ISSUE THREAD

**Issue by BlannyBlannyBlanc** [AstroDogeDX/CVRX#51]
Unable to acquire game code, and creator key does not work, either. Results in a 401 error. Either remove the option or please provide better instructions.

**Comment by AstroDogeDX** [comment]
Hi,

Your ABI Game Access Master Key can be found in the 'autologin.profile' file located at `...steamapps\common\ChilloutVR\ChilloutVR_Data` - however for simplicity we recommend you use the 'Import Game Credentials' button located at the top of the login page and navigate to the install directory of ChilloutVR - typically along the lines of `...steamapps\common\ChilloutVR\` - this will pull the details from your autologin.profile (and any other .profiles you may have configured) automatically for you.

![CVRX_b0un2pM7KW](https://github.com/AstroDogeDX/CVRX/assets/48888500/61804ea4-6ae8-4315-8e97-7d3f66ed7cfc)

The clarity of this is admittedly poor and a full redesign is planned, but CVRX development is currently on hiatus until after the new ABI Hub is deployed publicly. 

Many thanks~
